using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class BetterBodyCollider : MonoBehaviour {

	public GameObject head;
	public float radius = 0.2f;
	public float heightOffset = 0f;
	public float transformOffset = 0.66f;
	private float height = 1.0f;
	private CapsuleCollider col;
	private GameObject body;

	// Use this for initialization
	void Start () {
		body = new GameObject ("[Autogenerated] Body");
		body.AddComponent<CapsuleCollider>();
		col = body.GetComponent<CapsuleCollider> ();
		col.isTrigger = true;
		body.tag = "Player";
		body.transform.parent = head.transform;
		body.transform.position = head.transform.position;
	}
	
	// Update is called once per frame
	void Update () {
		Vector3 center = new Vector3 (head.transform.position.x, head.transform.position.y * transformOffset, head.transform.position.z);
		height = head.transform.position.y - heightOffset;
		col.radius = radius;
		col.height = height;
		body.transform.rotation = new Quaternion (0, 0, 0, transform.rotation.w);
		body.transform.position = center;

	}
}
